version: "2.2"

services:
  influxdb:
    image: influxdb:1.11.8
    ports:
    - "8086:8086"
    environment:
      "DOCKER_INFLUXDB_INIT_USERNAME": "admin"
      "DOCKER_INFLUXDB_INIT_PASSWORD": "password"
      "DOCKER_INFLUXDB_INIT_ORG": "test"
      "DOCKER_INFLUXDB_INIT_BUCKET": "test"